### ISSUE TITLE
Question to get attributes of app?

### ISSUE THREAD

**Issue by carvinchen** [bnoffer/owncloud-sharp#27] opened 2017-06-06 15:38 UTC
Hi, All

I can get a list of all apps (name), but i cant get the attributes of a app by using following codes:
`
     List<AppAttribute> calAttributeList = cloudClient.GetAttribute("calendar");
                foreach (AppAttribute userCalendar in calAttributeList)
                {
                    Console.WriteLine("\n Calendar APP " + userCalendar.App + " KEY: " + userCalendar.Key + " VALUE: " + userCalendar.value + "\n");
                    
                }
`
OUTPUT: no output...blank cells

And in Client.cs this one:

Line 892:  var path = "getattribute";  MAYBE IT IS THE REASON ?

Have any ideas?

Thanks! 

David

**Comment by bnoffer** [comment] 2017-06-06 19:11
I don't know if you posted this in one of your other issues, but could you provide me with the ownCloud version you are running?

**Comment by carvinchen** [comment] 2017-06-06 19:56
I am using the version 9.1.

**Comment by bnoffer** [comment] 2017-06-06 20:04
From what I can see the calls are going out fine. Checking the ownCloud source code for the API routes everything seems to be right. Checking the XML responses from the ownCloud server a proper OCS StautsCode of 100 is returned. I have to anticipate that this functionality has been disabled in more recent releases. Although I will investigate further once I have more free time at hand.

**Comment by carvinchen** [comment] 2017-06-06 20:24
Would you like to give me an example to get the value of app "calendar" of an user or show me how should i get the value of apps, if the functionality has been disabled? 

Thank you!

**Comment by bnoffer** [comment] 2017-06-06 20:57
The way you did it was just fine. The problem is, that for some reason the ownCloud servers (I tested both versions 8.2 and 9.1) have stopped providing these information:
´´´
<?xml version="1.0"?>
<ocs>
      <meta>
         <status>ok</status>
         <statuscode>100</statuscode>
         <message/>
      </meta>
   <data/>
</ocs>
´´´
As you can see with the status code the request has passed the API, but the server does not provide any data. This is not an issue of the library, but of the server itself.

**Comment by carvinchen** [comment] 2017-06-07 07:05
Thank you for answers! I am not sure if it is depending on the configuration of owncloud server or maybe i should import another open source Lib like WebDAVNET from NuGet? Maybe i should update the owncloud version to 10.0, but your project is only suitable for version 9.1, right? I am looking forward to your suggestions! Thanks! LG

**Comment by bnoffer** [comment] 2017-06-07 07:46
This library already uses a updated version of WebDAVNet, so there is no need for you to get another version from NuGet.

Upgrading to ownCloud 10 will probably not fix the availability of this feature.

The problem is that this part of the API is not really documented by the ownCloud documentation. The implementation used here is based on the [Python client library for ownCloud](https://github.com/owncloud/pyocclient) and as far as I remember my first implementation had worked. Probably still being on ownCloud 8.1.

I'll keep you updated once I find out more about this issue.

**Comment by bnoffer** [comment] 2017-06-07 08:33
Okay, now that I checked [the ownCloud source](https://github.com/owncloud/core/blob/master/lib/private/OCS/PrivateData.php) and took a peek into my databases the answer is obvious:

If the server has not stored any private attributes for that app, there is nothing to show. As a result the blank `<data/>` element is the correct result. You can check if your ownCloud server has stored any of these attributes by checing the `oc_privatedata` table in your database. In the case of all of my test installs this table is empty, so no attributes were logged.

**Comment by bnoffer** [comment] 2017-06-14 11:38
I am closing this issue, because it is not caused by the library, but by the ownCloud server behavior.

**Closed by bnoffer** 2017-06-14 11:38 UTC
Labels: OCS, wontfix
